version: '3.8'

services:
  lookup-distance-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lookup-distance-service
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    volumes:
      # Monta il file points_of_interest.json nella cartella host lookup-fe-distance2
      - ~/lookup-fe-distance2:/app/shared
      # Monta anche distance_cache.json per persistenza della cache
      - ~/lookup-fe-distance2/distance_cache.json:/app/distance_cache.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/distance?origin=test&destination=test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - lookup-distance-network

networks:
  lookup-distance-network:
    driver: bridge
