services:
  lookup-distance-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lookup-distance-service-prod
    ports:
      - "127.0.0.1:5001:5001"  # Bind only to localhost for security
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5001/distance?origin=test&destination=test')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - lookup-distance-network

networks:
  lookup-distance-network:
    driver: bridge
